spring:
  application:
    name: notification-service
  datasource:
    username: test
    password: test
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-service-group
    producer:
      acks: all
      # retries: 3
      properties:
        # retry.backoff.ms: 1000 # 1second delay between retries
        delivery.timeout.ms: 120000 # 2 minutes timeout for each request
        linger.ms: 0 # 0 ms delay between messages
        request.timeout.ms: 30000 # 30 seconds timeout for each request
server:
  port: 8081