spring:
  application:
    name: product-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-service-group
    producer:
      acks: all
      # retries: 3
      properties:
        # retry.backoff.ms: 1000 # 1 second delay between retries
        delivery.timeout.ms: 120000 # 2 minutes timeout for each request
        linger.ms: 0 # 0 ms delay between messages
        request.timeout.ms: 30000 # 30 seconds timeout for each request
      transaction-id-prefix: product-service-${random.value}-

  datasource:
    url: jdbc:postgresql://localhost:5432/product_service_eda
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        kafka:
          transaction: TRACE
        transaction: TRACE